### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by trifleneurotic** [trifleneurotic/EmbySonic#1]
Since version 1.13 of the Subsonic API, authentication supports a salted hash. Since that is not "reversible" in general, this plugin can either support the last version of the Subsonic API that doesn't support them (1.12), or throw away the name and the password from the Subsonic client and use, say, an API key already set at plugin end of things, but that seems a blatant security risk and I would not want to do that.

Notably, the Subsonic API spec says that the salted hash is the _recommended_ way for 1.13+, not the only way, so it appears we can support newer versions of the Subsonic API and still just use either plaintext or UTF-8 hex for the password, but that should come with the huge caveat to have encryption set up properly if accessing from outside one's local network.

This issue is a placeholder for this discussion.

**Comment by LukePulverenti** [comment]
The API key trick is the workaround that I had already thought of, so I guess I don't have much to suggest here.

**Comment by trifleneurotic** [comment]
> The API key trick is the workaround that I had already thought of, so I guess I do n't have much to suggest here.

@LukePulverenti 

No problem. I've finally made strides with authentication, returning a properly formed Subsonic XML response.

For this specific task, I didn't have any luck with the following:

- the `Service` classes in the `Emby.Api` namespace (likely because they aren't in the NuGet packages)
- the `Emby.ApiClient` (I think simply because it is just too old)
- using RestSharp (probably because assembly not packaged with Emby)

So at the moment I'm using classes in the `System.Net.Http` namespace to interface with Emby's API, although I think the cleanest solution would be to use the Emby `ApiClient` but it is years old.

Thoughts on proceeding with direct REST calls versus updating the ApiClient first for authentication, or instead just using a set API key that bypasses any authentication, in essence making authentication succeed every time?

**Comment by trifleneurotic** [comment]
Closing this issue for now as I have Subsonic-style authentication working, implemented with classes from the `System.Net.Http` namespace.
