### ISSUE TITLE
do you have a dll file i could use?

### ISSUE THREAD

**Issue by tonyt321** [trifleneurotic/EmbySonic#4]

**Comment by trifleneurotic** [comment]
Hi! Sorry for the delay. I certainly could send you a .DLL but let me go ahead and get make a release here within the next few days and you can download a .DLL from there.

**Comment by tonyt321** [comment]
sorry to ask again but would you be able to upload the .DLL file

**Comment by trifleneurotic** [comment]
> sorry to ask again but would you be able to upload the .DLL file

I know it has been almost a year since your comment, but I am back to working on this project starting now (four kids & various life events). You may have found an alternate solution in the meantime, but if you'd still like a .DLL, I can build one for you but just be advised that the API at this time is not feature-complete.

**Comment by tonyt321** [comment]
Thanks for the reply! I hope you are doing well. I would still love a dll
file as I this would mostly be to get my emby playlists onto Logitech media
server.

**Comment by trifleneurotic** [comment]
@tonyt321 

I have created a tagged pre-release (https://github.com/trifleneurotic/EmbySonic/releases/tag/v0.0.1.2-alpha) with an attached debug `.dll`. Just be sure to check out the release notes. But in short, it is not functional as a viable Subsonic API layer yet at all, and so will not work at this early stage. That said, feel free to open an issue so anything you run into can be tracked & addressed as work progresses if you'd like. High-level installation instructions are in the notes, and the README has been updated with this information as well.

**Comment by trifleneurotic** [comment]
@tonyt321 

Hello!

Wanted to check with you to see if you needed any further help or assistance at the moment?

Since I am actively working this project (at least part-time), I do plan to do more `.dll` releases as I implement more Subsonic API method groups so I was going to close this issue out.

**Comment by tonyt321** [comment]
so far it has installed, i havent had the time to fully test it yet but so far it seems to work
